version: '3'

services:
  # Infrastructure services
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartwatch_analytics
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./storage/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # Application services
  ingestion-server:
    build:
      context: ./ingestion
    ports:
      - "62333:62333"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  stream-processor:
    build:
      context: ./processor
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGODB_URI=mongodb://mongodb:27017/
      - POSTGRES_URI=postgresql://postgres:postgres@timescaledb:5432/smartwatch_analytics
    depends_on:
      - kafka
      - mongodb
      - timescaledb
      - ingestion-server

  query-api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@timescaledb:5432/smartwatch_analytics
    depends_on:
      - timescaledb

volumes:
  zookeeper_data:
  kafka_data:
  mongodb_data:
  timescaledb_data: